version: "3"

services:
  home:
    container_name: home
    build: ./Home
    ports:
      - 5000:5000
    networks:
      - test_network

  blog:
    container_name: blog
    build: ./Blog
    ports:
      - 8081:8081
    networks:
      - test_network
networks:
  test_network:
    driver: bridge
